<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace GPBMetadata;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8c010a0a617574682e70726f746f12046175746822180a0752657175657374120d0a05746f6b656e180120012809221a0a08526573706f6e7365120e0a06757365724964180120012809323a0a09546f6b656e697a6572122d0a0a636865636b546f6b656e120d2e617574682e526571756573741a0e2e617574682e526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

